name: Scheduled tasks

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight (00:00 UTC) every Sunday
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  update_videos_data:
    if: github.repository == 'bkhpanigha/hh-suttas'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U --pre "yt-dlp[default]"
        python -m pip install requests

    - name: Run fetch_youtube_data.py script
      run: python python/scripts/fetch_youtube_data.py

    - name: Commit and push changes if files were modified
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        changed=false
        
        if ! git diff --exit-code python/generated/available_videos.json; then
          git add python/generated/available_videos.json
          changed=true
        fi
        
        if ! git diff --exit-code python/generated/available_playlists.json; then
          git add python/generated/available_playlists.json
          changed=true
        fi
        
        if [ "$changed" = true ]; then
          git commit -m "Update Available Videos and Playlists Data"
          git push
        else
          echo "No changes to commit."
        fi
