name: Scheduled tasks

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight (00:00 UTC) every Sunday
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  update_videos_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install yt-dlp
        python -m pip install requests

    - name: Run fetchAvailableVideos.py script
      run: python python/scripts/fetch_videos_data.py

    - name: Commit and push changes if markdown files were created
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if ! git diff --exit-code python/generated/available_videos.json; then
          git add python/generated/available_videos.json
          git commit -m "Update Available Videos Data"
          git push
        else
          echo "No changes to commit."
        fi
